<h1>O projektu</h1>

<p>
    Tato stránka je školním projektem do předmětu Informační systémy na Fakultě informačních technologií Vysokého učení technického v Brně.
</p>

<h2>Použité technologie</h2>
<ul>
    <li>PHP 5.6</li>
    <li>HTML 5 + CSS 3</li>
    <li>MySQL (Maria DB)</li>
    <li>Knihovna JQuery</li>
</ul>

<p>
    Aplikace demonstruje použití MVC architektury.
</p>

<h2>Autor</h2>

Marek Šipoš (xsipos03)<br />
