<h1>Ztracené údaje</h1>

<p>
    Nemůžete se přihlásit? Pokud jste své údaje k internetovému bankovnictví ztratili nebo zapomněli, pomůžeme vám je obnovit.<br />
    Jednoduše zadejte e-mailovou adresu, kterou jste při registraci použili, a postupujte podle pokynů uvedených ve zprávě.
</p>
<p>
    Nemáte ještě účet? <a href="/registration">Zaregistrujte se</a> a využíjte našich služeb! Pokud své údaje znáte, můžete se <a href="/login">přihlásit</a>.
</p>

<?= $form->render() ?>
