
package calculators;

import java.awt.event.KeyEvent;
/**
 * Tato třída je graficka kalkulacka, ktera zakladni funkce pocita sama a specialni metody si vola z tridu math, kterou jsme si vytvorili.
 * @author Václav Stehlík, Marek Šipoš, Kristián Škrobánek, Tomáš Štveráček
 */
public class disp extends javax.swing.JFrame {

    // Possible operations
    public enum ops {
        NONE, ADD, SUB, MUL, DIV, POW, SQRT, FACT
    }
    
    // Possible stages
    public enum stages {
        FIRST, OPERATION, SECOND
    }

    // (INFO: Double loses accuracy for big numbers after ~15 numerals)
    public static final int DISPLAYLENGTH = 15; // Display length (for lock)
    public static final String TOOHIGH = "Chyba: cislo je mimo rozsah";
    public static final String NEGATIVESQRT = "Chyba: zaporna odmocnina";
    public static final String DIVIDEBYZERO = "Chyba: deleni nulou";
    
    double finumber = 0; // First input number
    double senumber = Double.NaN; // Second input number (for two operand operations)
    double exc = 1; // Amount of numbers on the Display
    ops operation = ops.NONE; // Actual operation
    boolean clearDisplay = false; // If display should be cleared on next button press
    stages stage = stages.FIRST; // What has user inputted
    java.awt.Font displayFont; // Used to restore previous font after error is shown

    /**
     * Tato metoda je konstruktor tridy. Vytvari novou instanci teto tridy.
     */
    public disp() {
        initComponents();
        Display.setEditable(false); // Proc to tu je? //aby se nedal editovat text
        displayFont = Display.getFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JTextField();
        buteq = new javax.swing.JButton();
        jPanelDigits = new javax.swing.JPanel();
        but4 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but0 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        butcomma = new javax.swing.JButton();
        but1 = new javax.swing.JButton();
        butchange = new javax.swing.JButton();
        jPanelOperations = new javax.swing.JPanel();
        butmul = new javax.swing.JButton();
        butadd = new javax.swing.JButton();
        butdiv = new javax.swing.JButton();
        butpow = new javax.swing.JButton();
        butsub = new javax.swing.JButton();
        butfac = new javax.swing.JButton();
        butC = new javax.swing.JButton();
        butsqrt = new javax.swing.JButton();
        jMenuBarHlavni = new javax.swing.JMenuBar();
        jMenuNapoveda = new javax.swing.JMenu();
        jMenuItemOProgramu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fluidum calculator");
        setBackground(javax.swing.UIManager.getDefaults().getColor("MenuBar.foreground"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(302, 326));
        setMinimumSize(new java.awt.Dimension(302, 326));
        setResizable(false);
        setSize(new java.awt.Dimension(302, 326));

        Display.setEditable(false);
        Display.setFont(new java.awt.Font("Noto Sans", 0, 30)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setText("0");
        Display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Display.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Display.setRequestFocusEnabled(false);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        Display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DisplayKeyPressed(evt);
            }
        });

        buteq.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buteq.setText("=");
        buteq.setFocusable(false);
        buteq.setMaximumSize(new java.awt.Dimension(48, 37));
        buteq.setMinimumSize(new java.awt.Dimension(48, 37));
        buteq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buteqActionPerformed(evt);
            }
        });

        jPanelDigits.setAlignmentX(0.0F);
        jPanelDigits.setAlignmentY(0.0F);

        but4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but4.setText("4");
        but4.setFocusable(false);
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });

        but7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but7.setText("7");
        but7.setFocusable(false);
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });

        but2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but2.setText("2");
        but2.setFocusable(false);
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but3.setText("3");
        but3.setFocusable(false);
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });

        but5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but5.setText("5");
        but5.setFocusable(false);
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });

        but9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but9.setText("9");
        but9.setFocusable(false);
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });

        but6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but6.setText("6");
        but6.setFocusable(false);
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });

        but0.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but0.setText("0");
        but0.setFocusable(false);
        but0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but0ActionPerformed(evt);
            }
        });

        but8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but8.setText("8");
        but8.setFocusable(false);
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });

        butcomma.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butcomma.setText(",");
        butcomma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        butcomma.setFocusable(false);
        butcomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcommaActionPerformed(evt);
            }
        });

        but1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        but1.setText("1");
        but1.setToolTipText("");
        but1.setFocusable(false);
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });

        butchange.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butchange.setText("±");
        butchange.setFocusable(false);
        butchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butchangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDigitsLayout = new javax.swing.GroupLayout(jPanelDigits);
        jPanelDigits.setLayout(jPanelDigitsLayout);
        jPanelDigitsLayout.setHorizontalGroup(
            jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDigitsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDigitsLayout.createSequentialGroup()
                        .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDigitsLayout.createSequentialGroup()
                                .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDigitsLayout.createSequentialGroup()
                                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(but0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butcomma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butchange, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDigitsLayout.createSequentialGroup()
                        .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanelDigitsLayout.setVerticalGroup(
            jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDigitsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDigitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butcomma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butchange, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        butmul.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butmul.setText("*");
        butmul.setFocusable(false);
        butmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butmulActionPerformed(evt);
            }
        });

        butadd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butadd.setText("+");
        butadd.setFocusable(false);
        butadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaddActionPerformed(evt);
            }
        });

        butdiv.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butdiv.setText("/");
        butdiv.setFocusable(false);
        butdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdivActionPerformed(evt);
            }
        });

        butpow.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butpow.setText("^");
        butpow.setFocusable(false);
        butpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butpowActionPerformed(evt);
            }
        });

        butsub.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butsub.setText("–");
        butsub.setToolTipText("");
        butsub.setFocusable(false);
        butsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsubActionPerformed(evt);
            }
        });

        butfac.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butfac.setText("!");
        butfac.setFocusable(false);
        butfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butfacActionPerformed(evt);
            }
        });

        butC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butC.setText("C");
        butC.setFocusable(false);
        butC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCActionPerformed(evt);
            }
        });

        butsqrt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        butsqrt.setText("√");
        butsqrt.setFocusable(false);
        butsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsqrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOperationsLayout = new javax.swing.GroupLayout(jPanelOperations);
        jPanelOperations.setLayout(jPanelOperationsLayout);
        jPanelOperationsLayout.setHorizontalGroup(
            jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperationsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelOperationsLayout.createSequentialGroup()
                        .addComponent(butadd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butmul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOperationsLayout.createSequentialGroup()
                        .addComponent(butC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butfac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOperationsLayout.createSequentialGroup()
                        .addComponent(butsub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOperationsLayout.createSequentialGroup()
                        .addComponent(butpow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanelOperationsLayout.setVerticalGroup(
            jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperationsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butfac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOperationsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butpow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butmul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butsub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );

        jMenuNapoveda.setText("Nápověda");

        jMenuItemOProgramu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemOProgramu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculators/calc.png"))); // NOI18N
        jMenuItemOProgramu.setText("O programu");
        jMenuItemOProgramu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOProgramuActionPerformed(evt);
            }
        });
        jMenuNapoveda.add(jMenuItemOProgramu);

        jMenuBarHlavni.add(jMenuNapoveda);

        setJMenuBar(jMenuBarHlavni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buteq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDigits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jPanelOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDigits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buteq, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Fluidum Calculator");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*Tato metoda reaguje na udalost tlacitka '=' a v teto metode probihaji veskere vypocty*/
    private void buteqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buteqActionPerformed

        math useMath = new math();
        double result = 0;
        
        /* Prepare finumber and senumber for math operations */
        switch (stage) {
            // First number is on the screen and user pressed '='
            case FIRST:
                // (INFO: operation and finumber could be set -> allows multi '=' presses)
                finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
                break;
            /* '=' operation executes after operator has been clicked */
            case OPERATION:
                // '=' pressed after one operand opperation = use finumber twice
                if (operation != ops.FACT && operation != ops.SQRT) {
                    senumber = finumber;
                    stage = stages.SECOND;
                }
                // (else its regular usage of FACT or SQRT)
                break;
            /* '=' pressed after everything is ready for two operand operation */
            case SECOND:
                senumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
                break;
        }
        
        /* Do math */
        switch (operation) {
            case ADD:
                result = useMath.add(finumber, senumber);
                break;
            case SUB:
                result = useMath.subtract(finumber, senumber);
                break;
            case MUL:
                result = useMath.multiply(finumber, senumber);
                break;
            case DIV:
                result = useMath.divide(finumber, senumber);
                break;
            case POW:
                result = useMath.power(finumber, senumber);
                break;
            case FACT:
                result = useMath.factorial(finumber);
                break;
            case SQRT:
                result = useMath.squareRoot(finumber);
                break;
            case NONE:
                result = finumber;
        }

        // Handle changing amount of maximum decimal numbers
        String ans;
        String ansWithoutDecimals = String.format("%.0f", java.lang.Math.abs(result));
        int maxDecimals = DISPLAYLENGTH - ansWithoutDecimals.length();
        String numberSigns;
        if (maxDecimals > 0) {
            numberSigns = ".";
        }
        else {
            numberSigns = "";
        }
        for (int i = 0; i < maxDecimals; i++) {
            numberSigns += "#";
        }

        java.text.DecimalFormat fmt = new java.text.DecimalFormat("0" + numberSigns);
        // (INFO: pokud je locale systemu cestina, tento replaceAll neni vzdy nutny)
        ans = fmt.format(result).replaceAll("\\.", ",");
        
        /* Display results */
        if (ansWithoutDecimals.length() > DISPLAYLENGTH || useMath.isTooLarge()) {
            displayError(TOOHIGH);
        }
        else if (useMath.isNegativeSqrt()) {
            displayError(NEGATIVESQRT);
        }
        else if (useMath.isDivideByZero()) {
            displayError(DIVIDEBYZERO);
        }
        else {
            Display.setText(ans);
            clearDisplay = true;

            stage = stages.FIRST;
        }

    }//GEN-LAST:event_buteqActionPerformed

    /*Tato metoda reaguje na udalost tlacitka jedna*/
    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed

        doDigitClick("1");
        
    }//GEN-LAST:event_but1ActionPerformed

    /*Tato metoda reaguje na udalost tlacitka dva*/
    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed

        doDigitClick("2");
        
    }//GEN-LAST:event_but2ActionPerformed

    /*Tato metoda reaguje na udalost tlacitka tri*/
    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed

        doDigitClick("3");
        
    }//GEN-LAST:event_but3ActionPerformed

        /*Tato metoda reaguje na udalost tlacitka ctyri*/
    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed

        doDigitClick("4");
        
    }//GEN-LAST:event_but4ActionPerformed

        /*Tato metoda reaguje na udalost tlacitka pet*/
    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed

        doDigitClick("5");
        
    }//GEN-LAST:event_but5ActionPerformed

        /*Tato metoda reaguje na udalost tlacitka sest*/
    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed

        doDigitClick("6");
        
    }//GEN-LAST:event_but6ActionPerformed

    /*Tato metoda reaguje na udalost tlacitka sedm*/
    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed

        doDigitClick("7");
        
    }//GEN-LAST:event_but7ActionPerformed

        /*Tato metoda reaguje na udalost tlacitka osm*/

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed

        doDigitClick("8");
        
    }//GEN-LAST:event_but8ActionPerformed

    /*Tato metoda reaguje na udalost tlacitka devet*/
    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed

        doDigitClick("9");
        
    }//GEN-LAST:event_but9ActionPerformed

    /*Tato metoda reaguje na udalost tlacitka nula*/
    private void but0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but0ActionPerformed

        doDigitClick("0");
        
    }//GEN-LAST:event_but0ActionPerformed

    /*Tato metoda reaguje na udalost tlacitka desetinne carky*/
    private void butcommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcommaActionPerformed
        if (clearDisplay) {
            clearDisplay();
            Display.setText("0");
            setExc(1);
        }
        // Write comma only if there isn't one already
        if (Display.getText().indexOf(',') == -1) {
            Display.setText(Display.getText() + ",");
        }
    }//GEN-LAST:event_butcommaActionPerformed

    /*Tato metoda reaguje na udalost tlacitka scitani*/
    private void butaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaddActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
            clearDisplay = true;
            setExc(0);
        }
        Display.setText("+");
        operation = ops.ADD;
        
    }//GEN-LAST:event_butaddActionPerformed

    /*Tato metoda reaguje na udalost tlacitka rozdilu*/
    private void butsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsubActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
            clearDisplay = true;
            setExc(0);
        }
        Display.setText("-");
        operation = ops.SUB;

    }//GEN-LAST:event_butsubActionPerformed

    /*Tato metoda reaguje na udalost tlacitka soucinu*/
    private void butmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butmulActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
            clearDisplay = true;
            setExc(0);
        }
        Display.setText("*");
        operation = ops.MUL;

    }//GEN-LAST:event_butmulActionPerformed

    /*Tato metoda reaguje na udalost tlacitka podilu*/
    private void butdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdivActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
            clearDisplay = true;
            setExc(0);
        }
        Display.setText("/");
        operation = ops.DIV;

    }//GEN-LAST:event_butdivActionPerformed

    /*Tato metoda reaguje na udalost tlacitka faktorialu*/
    private void butfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butfacActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
        }
        operation = ops.FACT;
        buteq.doClick(1);

    }//GEN-LAST:event_butfacActionPerformed

    /*Tato metoda reaguje na udalost tlacitka odmocniny*/
    private void butsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsqrtActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
        }
        operation = ops.SQRT;
        buteq.doClick(1);

    }//GEN-LAST:event_butsqrtActionPerformed

    /*Tato metoda reaguje na udalost tlacitka mocniny*/
    private void butpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butpowActionPerformed

        if (stage != stages.OPERATION) {
            if (stage == stages.SECOND) {
                buteq.doClick(1);
            }
            finumber = Double.parseDouble(Display.getText().replaceAll(",", "."));
            stage = stages.OPERATION;
            clearDisplay = true;
            setExc(0);
        }
        Display.setText("^");
        operation = ops.POW;

    }//GEN-LAST:event_butpowActionPerformed

    /*Tato metoda reaguje na udalost tlacitko '+/-'*/
    private void butchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butchangeActionPerformed
        if (!Display.getText().equals("0")) {
            if (Display.getText().charAt(0) == '-') {
                Display.setText(Display.getText().substring(1, Display.getText().length()));
            }
            else {
                Display.setText("-" + Display.getText());
            }
        }
    }//GEN-LAST:event_butchangeActionPerformed

    /*Tato metoda reaguje na udalost tlacitka 'C'*/
    private void butCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCActionPerformed

        // Display stuff
        clearDisplay();
        Display.setFont(displayFont);
        Display.setText("0");
        setExc(1);

        // Logic stuff
        operation = ops.NONE;
        finumber = 0;
        senumber = Double.NaN;
        waitForC(false);

    }//GEN-LAST:event_butCActionPerformed

    /*Tato metoda reaguje na udalost tlacitek z klavesnice*/
    private void DisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisplayKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_1 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD1) {
            but1.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_2 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD2) {
            but2.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_3 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD3) {
            but3.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_4 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD4) {
            but4.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_5 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD5) {
            but5.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_6 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD6) {
            but6.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_7 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD7) {
            but7.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_8 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD8) {
            but8.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_9 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD9) {
            but9.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_0 ||
            evt.getKeyCode() == KeyEvent.VK_NUMPAD0) {
            but0.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ADD ||
            evt.getKeyCode() == KeyEvent.VK_PLUS) {
            butadd.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_SUBTRACT ||
            evt.getKeyCode() == KeyEvent.VK_MINUS) {
            butsub.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_MULTIPLY) {
            butmul.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_DIVIDE) {
            butdiv.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_EXCLAMATION_MARK) {
            butfac.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_EQUALS ||
            evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buteq.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_PERIOD ||
            evt.getKeyCode() == KeyEvent.VK_DECIMAL ||
            evt.getKeyCode() == KeyEvent.VK_COMMA) {
            butcomma.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            butC.doClick(1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            doBackSpace();
        }
    }//GEN-LAST:event_DisplayKeyPressed

    /*Tato metoda reaguje na udalost tlacitka napoveda*/
    private void jMenuItemOProgramuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOProgramuActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, "Fluidum Calculator\n"
                + "Program vznikl jako školní projekt do předmětu IVS\n\n"
                + "Autoři:\n"
                + "Václav Stehlík\n"
                + "Marek Šipoš\n"
                + "Kristián Škrobánek\n"
                + "Tomáš Štveráček\n\n"
                + "FIT VUT, 2016", "O programu", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItemOProgramuActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed
    
    /** 
     * Change internal amount of chars on display, controls locking of input buttons 
     * @param n pocet znaku na displeji
     */
    public void setExc(double n) {
        exc = n;
        if (exc < 0) { exc = 0; }
        // Enable buttons
        if (exc < DISPLAYLENGTH) {
            for (int i = 0; i < jPanelDigits.getComponentCount(); i++) {
                jPanelDigits.getComponent(i).setEnabled(true);
            }
        }
        // Disable buttons
        else {
            for (int i = 0; i < jPanelDigits.getComponentCount(); i++) {
                jPanelDigits.getComponent(i).setEnabled(false);
            }
            butchange.setEnabled(true);
        }
    }

    /* Lock everything except 'C' button */
    public void waitForC(boolean wait) {
        if (wait) {
            for (int i = 0; i < jPanelDigits.getComponentCount(); i++) {
                jPanelDigits.getComponent(i).setEnabled(false);
            }
            for (int i = 0; i < jPanelOperations.getComponentCount(); i++) {
                jPanelOperations.getComponent(i).setEnabled(false);
            }
            buteq.setEnabled(false);
            butC.setEnabled(true);
        }
        else {
            for (int i = 0; i < jPanelDigits.getComponentCount(); i++) {
                jPanelDigits.getComponent(i).setEnabled(true);
            }
            for (int i = 0; i < jPanelOperations.getComponentCount(); i++) {
                jPanelOperations.getComponent(i).setEnabled(true);
            }
            buteq.setEnabled(true);
        }
    }

    /**
     * Napise chybu na displej
     */
    public void displayError(String error) {
        float size = Display.getFont().getSize();
        waitForC(true);
        Display.setFont(Display.getFont().deriveFont(size-8));
        Display.setText(error);
    }
    
    /**
     * Napise jedno cislo na displej
     */
    public void doDigitClick(String n) {
        // User is now giving second operand
        if (stage == stages.OPERATION) {
            stage = stages.SECOND;
        }
        // User is giving new input (like after pressing 'C'
        if (stage == stages.FIRST && operation != ops.NONE) {
            operation = ops.NONE;
        }
        // There was just '0', so overwrite it
        if (Display.getText().equals("0")) {
            clearDisplay = true;
        }
        // If we should overwrite display, we'll do
        if (clearDisplay) {
            clearDisplay();
        }
        // Add digit to Display
        Display.setText(Display.getText() + n);
        setExc(exc+1);
    }
    
    /**
     * Smaze jeden znak z displeje
     */
    public void doBackSpace() {
        if (!clearDisplay) {
            if (Display.getText().length() > 1) {
                Display.setText(Display.getText().substring(0, Display.getText().length()-1));
                setExc(exc-1);
            }
            else {
                Display.setText("0");
                setExc(1);
            }
        }
    }

    /**
     * Tato metoda vycisti displej
     */
    public void clearDisplay() {
        Display.setText("");
        setExc(0);
        clearDisplay = false;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException |
                 InstantiationException |
                 IllegalAccessException |
                 javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(disp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new disp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JButton but0;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JButton butC;
    private javax.swing.JButton butadd;
    private javax.swing.JButton butchange;
    private javax.swing.JButton butcomma;
    private javax.swing.JButton butdiv;
    private javax.swing.JButton buteq;
    private javax.swing.JButton butfac;
    private javax.swing.JButton butmul;
    private javax.swing.JButton butpow;
    private javax.swing.JButton butsqrt;
    private javax.swing.JButton butsub;
    private javax.swing.JMenuBar jMenuBarHlavni;
    private javax.swing.JMenuItem jMenuItemOProgramu;
    private javax.swing.JMenu jMenuNapoveda;
    private javax.swing.JPanel jPanelDigits;
    private javax.swing.JPanel jPanelOperations;
    // End of variables declaration//GEN-END:variables
}
